# README: See git commit message for `f5d0baabdba6ec5c62356f9f505b4c9058e25e6e` for more information.

# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application

# metadata:
#   name: kubedoom
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io

# spec:
#   project: infrastructure

#   sources:
#     # Kustomize
#     - repoURL: https://github.com/CMDR-JohnAlex/sidewinder-cluster-gitops.git
#       targetRevision: main
#       path: infrastructure/kubedoom/kustomize

#   destination:
#     server: https://kubernetes.default.svc
#     namespace: kubedoom

#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true

#     syncOptions:
#       - ServerSideApply=true
#       - CreateNamespace=true
