---
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: infrastructure

  sources:
    # Helm chart
    # https://github.com/bitnami/sealed-secrets
    # https://github.com/bitnami/sealed-secrets/tree/main/helm/sealed-secrets
    - repoURL: https://bitnami.github.io/sealed-secrets
      chart: sealed-secrets
      targetRevision: 2.19.1
      helm:
        valueFiles:
          - $values/infrastructure/sealed-secrets/helm/values.yaml

    # Values repository
    - repoURL: https://github.com/CMDR-JohnAlex/sidewinder-cluster-gitops.git
      targetRevision: main
      ref: values

    # Resources
    # - repoURL: https://github.com/CMDR-JohnAlex/sidewinder-cluster-gitops.git
    #   targetRevision: main
    #   path: infrastructure/sealed-secrets/kustomize

  destination:
    server: https://kubernetes.default.svc
    namespace: secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
