# Required for plain DNS.
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute

metadata:
  name: homepage-dns-tcp

spec:
  parentRefs:
    - name: dns-gateway
      namespace: envoy-gateway-system
      sectionName: dns-tcp

  rules:
    - backendRefs:
        - name: adguard-home
          port: 53
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute

metadata:
  name: homepage-dns-udp

spec:
  parentRefs:
    - name: dns-gateway
      namespace: envoy-gateway-system
      sectionName: dns-udp

  rules:
    - backendRefs:
        - name: adguard-home
          port: 53

# Required for running a DHCP server.
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute

metadata:
  name: homepage-dhcp-udp

spec:
  parentRefs:
    - name: dns-gateway
      namespace: envoy-gateway-system
      sectionName: dhcp-udp

  rules:
    - backendRefs:
        - name: adguard-home
          port: 67
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute

metadata:
  name: homepage-dhcp-tcp

spec:
  parentRefs:
    - name: dns-gateway
      namespace: envoy-gateway-system
      sectionName: dhcp-tcp

  rules:
    - backendRefs:
        - name: adguard-home
          port: 68
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute

metadata:
  name: homepage-dhcp-udp2

spec:
  parentRefs:
    - name: dns-gateway
      namespace: envoy-gateway-system
      sectionName: dhcp-udp2

  rules:
    - backendRefs:
        - name: adguard-home
          port: 68

# Required for the admin panel and for running a HTTPS/DNS-over-HTTPS server.
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute

metadata:
  name: homepage-http-tcp

spec:
  parentRefs:
    - name: dns-gateway
      namespace: envoy-gateway-system
      sectionName: http-tcp

  rules:
    - backendRefs:
        - name: adguard-home
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute

metadata:
  name: homepage-https-tcp

spec:
  parentRefs:
    - name: dns-gateway
      namespace: envoy-gateway-system
      sectionName: https-tcp

  rules:
    - backendRefs:
        - name: adguard-home
          port: 443
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute

metadata:
  name: homepage-https-udp

spec:
  parentRefs:
    - name: dns-gateway
      namespace: envoy-gateway-system
      sectionName: https-udp

  rules:
    - backendRefs:
        - name: adguard-home
          port: 443
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute

metadata:
  name: homepage-https-tcp2

spec:
  parentRefs:
    - name: dns-gateway
      namespace: envoy-gateway-system
      sectionName: https-tcp2

  rules:
    - backendRefs:
        - name: adguard-home
          port: 3000

# Required for running a DNS-over-TLS server.
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute

metadata:
  name: homepage-tls-tcp

spec:
  parentRefs:
    - name: dns-gateway
      namespace: envoy-gateway-system
      sectionName: tls-tcp

  rules:
    - backendRefs:
        - name: adguard-home
          port: 853

# Required for running a DNS-over-QUIC server.
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute

metadata:
  name: homepage-quic-udp

spec:
  parentRefs:
    - name: dns-gateway
      namespace: envoy-gateway-system
      sectionName: quic-udp

  rules:
    - backendRefs:
        - name: adguard-home
          port: 853

# Required for running a DNSCrypt server.
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute

metadata:
  name: homepage-dnscrypt-tcp

spec:
  parentRefs:
    - name: dns-gateway
      namespace: envoy-gateway-system
      sectionName: dnscrypt-tcp

  rules:
    - backendRefs:
        - name: adguard-home
          port: 5443
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute

metadata:
  name: homepage-dnscrypt-udp

spec:
  parentRefs:
    - name: dns-gateway
      namespace: envoy-gateway-system
      sectionName: dnscrypt-udp

  rules:
    - backendRefs:
        - name: adguard-home
          port: 5443
