---
apiVersion: v1
kind: Service
metadata:
  name: kubeinvaders-svc
spec:
  type: ClusterIP
  selector:
    app: kubeinvaders-pod
  ports:
    - name: kinv-http-out
      protocol: TCP
      port: 80
      targetPort:  kinv-http
