---
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: jellyfin-dev
  namespace: argocd

spec:
  project: workloads

  sources:
    # Helm chart
    - repoURL: https://jellyfin.github.io/jellyfin-helm
      chart: jellyfin
      targetRevision: 3.2.0 # WARN: When updating to 3.3.0, see issue: https://github.com/jellyfin/jellyfin-helm/issues/133
      helm:
        valueFiles:
          - $values/workloads/jellyfin/values-common.yaml
          - $values/workloads/jellyfin/values-dev.yaml

    # Values repository
    - repoURL: https://github.com/CMDR-JohnAlex/sidewinder-cluster-gitops.git
      targetRevision: main
      ref: values

    # Extra resources - Kustomize
    - repoURL: https://github.com/CMDR-JohnAlex/sidewinder-cluster-gitops.git
      targetRevision: main
      path: workloads/jellyfin/resources/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: media-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
