---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler

metadata:
  name: sftpgo-prod

spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: sftpgo-prod

  updatePolicy:
    updateMode: "Off"
