---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig

metadata:
  name: alertmanager-webhook-ntfy
  namespace: kube-system

spec:
  route:
    receiver: alertmanager-webhook-ntfy
    matchers:
      - name: alertname
        matchType: "!="
        value: InfoInhibitor

    groupBy:
      - alertname
      - namespace

    groupWait: 10s
    groupInterval: 5m
    repeatInterval: 12m

  receivers:
    - name: alertmanager-webhook-ntfy
      webhookConfigs:
        - url: http://alertmanager-webhook-ntfy-svc.monitoring.svc.cluster.local:80/alertmanager
          sendResolved: true

---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig

metadata:
  name: alertmanager-webhook-ntfy
  namespace: monitoring

spec:
  route:
    receiver: alertmanager-webhook-ntfy
    matchers:
      - name: alertname
        matchType: "!="
        value: InfoInhibitor

    groupBy:
      - alertname
      - namespace

    groupWait: 10s
    groupInterval: 5m
    repeatInterval: 12m

  receivers:
    - name: alertmanager-webhook-ntfy
      webhookConfigs:
        - url: http://alertmanager-webhook-ntfy-svc.monitoring.svc.cluster.local:80/alertmanager
          sendResolved: true
