---
# These entries are shared between all the Immich components

controllers:
  main:
    containers:
      main:
        image:
          tag: v3.1.0

immich:

# Dependencies

valkey:
  enabled: false

# Immich components

server:
  enabled: false

machine-learning:
  enabled: false
