---
# https://argo-cd.readthedocs.io/en/stable/user-guide/application-set/
# https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: homepage
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          # - access: internal
          #   namespace: homepage-internal
          - access: general
            namespace: homepage-general

  template:
    metadata:
      name: 'homepage-{{access}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io

    spec:
      project: workloads
      sources:
        # Kustomize
        - repoURL: https://github.com/CMDR-JohnAlex/sidewinder-cluster-gitops.git
          targetRevision: main
          path: workloads/homepage/kustomize/overlays/{{access}}

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
