---
# https://argo-cd.readthedocs.io/en/stable/user-guide/application-set/
# https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: immich
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: immich-dev
            targetRevision: 0.13.1
          - env: prod
            namespace: immich-prod
            targetRevision: 0.13.1

  template:
    metadata:
      name: 'immich-{{env}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io

    spec:
      project: workloads
      sources:
        # Helm chart
        - repoURL: ghcr.io/immich-app/immich-chart
          chart: immich
          targetRevision: '{{targetRevision}}'
          helm:
            valueFiles:
              - $values/workloads/immich/helm/values-common.yaml
              - $values/workloads/immich/helm/values-{{env}}.yaml

        # Values repository
        - repoURL: https://github.com/CMDR-JohnAlex/sidewinder-cluster-gitops.git
          targetRevision: main
          ref: values

        # Kustomize
        - repoURL: https://github.com/CMDR-JohnAlex/sidewinder-cluster-gitops.git
          targetRevision: main
          path: workloads/immich/kustomize/overlays/{{env}}

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
