---
# https://argo-cd.readthedocs.io/en/stable/user-guide/application-set/
# https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: nginx
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: nginx-dev
          - env: prod
            namespace: nginx-prod

  template:
    metadata:
      name: 'nginx-{{env}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io

    spec:
      project: workloads
      sources:
        # Kustomize
        - repoURL: https://github.com/CMDR-JohnAlex/sidewinder-cluster-gitops.git
          targetRevision: main
          path: workloads/nginx/kustomize/overlays/{{env}}

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
