---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubedoom-deployment
  name: kubedoom
spec:
  replicas: 0
  selector:
    matchLabels:
      app: kubedoom-pod
  template:
    metadata:
      labels:
        app: kubedoom-pod
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom-rbac
      containers:
        - image: ghcr.io/storax/kubedoom:latest
          # env:
          #   - name: NAMESPACE
          #     value: default
          name: kubedoom
          ports:
            - containerPort: 5900
              name: vnc
