---
apiVersion: v1
kind: ConfigMap

metadata:
  name: homepage

  labels:
    app.kubernetes.io/name: homepage

data:
  kubernetes.yaml: |
    mode: disabled

  settings.yaml: |
    title: Sidewinder Cluster
    description: Sidewinder Cluster's Homepage
    # favicon: <URL or PATH>

    # TODO: https://gethomepage.dev/configs/settings/#background-image
    # TODO: https://gethomepage.dev/configs/settings/#background-opacity-filters
    # TODO: https://gethomepage.dev/configs/settings/#card-background-blur

    # TODO: https://gethomepage.dev/configs/settings/#progressive-web-app-pwa

    layout:
      Cluster & Docs:
        style: column
        columns: 1
      Media & Entertainment:
        style: column
        columns: 2
      Arr Stack:
        style: row
        columns: 4
      Productivity:
        style: row
        columns: 3
      Home & Network:
        style: row
        columns: 4
      Social:
        style: row
        columns: 2

  custom.css: ""
  custom.js: ""

  bookmarks.yaml: |
    - Useful Links:
      - Kubernetes Docs:
        - abbr: K8s
          icon: kubernetes.svg
          href: https://kubernetes.io/docs/home
          description: Kubernetes Documentation
      - Kubernetes Concepts:
        - abbr: K8s
          icon: kubernetes.svg
          href: https://kubernetes.io/docs/concepts
          description: Kubernetes Concepts
      - Kubernetes Reference:
        - abbr: K8s
          icon: kubernetes.svg
          href: https://kubernetes.io/docs/reference
          description: Kubernetes Reference
      - Arch Linux Wiki:
        - abbr: Arch
          icon: arch-linux.svg
          href: https://wiki.archlinux.org
          description: Linux issues? Look here!

    - Other Links:
      - selfhost:
        - abbr: sh
          icon: selfh-st.svg
          href: https://selfh.st/apps
          description: List of self-hosted apps. Find something you like? Request it!

  services.yaml: |
    - Cluster & Docs:
        - Cluster Documentation:
            icon: nginx.svg
            href: https://docs.sidewinder.lan
            description: "Read me first! Guides & Info."
        - Grafana:
            icon: grafana.svg
            href: https://grafana.sidewinder.lan
            description: "Monitor the Kubernetes cluster."
        - Ntfy:
            icon: ntfy.svg
            href: https://ntfy.sidewinder.lan/home-announcements
            description: "Cluster announcements and alerts."

    - Media & Entertainment:
        - Jellyfin:
            icon: jellyfin.svg
            href: https://jellyfin.sidewinder.lan
            description: "Watch movies and TV shows."
        - Navidrome:
            icon: navidrome.svg
            href: https://navidrome.sidewinder.lan
            description: "Listen to our music library."
        - Feishin:
            icon: feishin.svg
            href: https://feishin.sidewinder.lan
            description: "Beautiful Web UI for Navidrome."
        - Immich:
            icon: immich.svg
            href: https://immich.sidewinder.lan
            description: "Family photo and video backups."
        - Minecraft Server:
            icon: minecraft.svg
            href: https://mc.sidewinder.lan
            description: "Family Minecraft Server."

    - Arr Stack:
        - EMPTY 1:
            href: https://homepage.sidewinder.lan
            description: "Placeholder."

    - Productivity:
        # Vikunja
        # Forgejo
        # SFTPGo
        - EMPTY 2:
            href: https://homepage.sidewinder.lan
            description: "Placeholder."

    - Home & Network:
        # Home Assistant
        # Pi-Hole
        # AdGuard Home
        # Technitium
        - EMPTY 3:
            href: https://homepage.sidewinder.lan
            description: "Placeholder."

    - Social:
        # Matrix
        # Mastodon
        - EMPTY 4:
            href: https://homepage.sidewinder.lan
            description: "Placeholder."

  widgets.yaml: |
    - logo:
      icon: homepage.svg

    - greeting:
      text_size: xl
      text: Sidewinder Cluster

    - search:
        provider: duckduckgo
        target: _blank

    - datetime:
      text_size: xl
      format:
        timeStyle: short
        hourCycle: h23

  docker.yaml: ""
  proxmox.yaml: ""
