---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage

spec:
  replicas: 1
  revisionHistoryLimit: 3

  template:
    spec:
      containers:
        - name: homepage
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "$(MY_POD_IP):3000,homepage.sidewinder.lan,sidewinder.lan" # See gethomepage.dev/installation/#homepage_allowed_hosts . Value before the comma is required for the k8s probe
