---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: nginx-i-36f8a5b8-data

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: usb-flash

  resources:
    requests:
      storage: 1Mi
