---
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: music-stack-dev
  namespace: argocd

spec:
  project: workloads

  sources:
    # Kustomize
    - repoURL: https://github.com/CMDR-JohnAlex/sidewinder-cluster-gitops.git
      targetRevision: main
      path: workloads/music-stack/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: media-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
