---
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: music-stack-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: workloads

  sources:
    # Kustomize
    - repoURL: https://github.com/CMDR-JohnAlex/sidewinder-cluster-gitops.git
      targetRevision: main
      path: workloads/music-stack/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: media-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
