---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: media-prod

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml
  - path: gateway-patch.yaml

commonLabels:
  instance: prod
