---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: sftpgo-data-pvc

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: hdd-general

  resources:
    requests:
      storage: 4Mi
