---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/deployment.yaml
  - resources/configmap.yaml
  - resources/svc.yaml
  - resources/alertmanagerconfig.yaml
