---
# https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1alpha1.AlertmanagerConfig
# https://prometheus-operator.dev/docs/developer/alerting/
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig

metadata:
  name: discord
  namespace: kube-system

spec:
  route:
    receiver: discord
    # matchers:
    #   - name: alertname
    #     matchType: "="
    #     value: AlertmanagerTest

    groupBy:
      - alertname
      - namespace

    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h

  receivers:
    - name: discord
      discordConfigs:
        - apiURL:
            name: alertmanager-discord-webhook
            key: webhook-url
          sendResolved: true
          username: "sidewinder-cluster (kube-system)"
          # avatarURL: "http://example.com"

---
# https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1alpha1.AlertmanagerConfig
# https://prometheus-operator.dev/docs/developer/alerting/
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig

metadata:
  name: discord
  namespace: monitoring

spec:
  route:
    receiver: discord
    # matchers:
    #   - name: alertname
    #     matchType: "="
    #     value: AlertmanagerTest

    groupBy:
      - alertname
      - namespace

    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h

  receivers:
    - name: discord
      discordConfigs:
        - apiURL:
            name: alertmanager-discord-webhook
            key: webhook-url
          sendResolved: true
          username: "sidewinder-cluster (monitoring)"
          # avatarURL: "http://example.com"
