---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-discord-webhook
  namespace: kube-system
spec:
  encryptedData:
    webhook-url: AgAGsvOrc6OJKHMNLl4LxNhkXGKZEyv7A0qPMv0TTgzKbCPQ+Ne5bOiTYVbp0zSCEY/Wzgm+yQh7Bf3ltxyklmYN+nec06iIROkcMvNCJYb6tDWDi6hq/QzNivwXdSNhlUpZruZxsLVIDNrot6uMgtvvv/oMzY6hajzNk91wuIJ+iz2LEUVxm+epN4UIETGJsMuAyh80LlVehKC7aUpbgpNCEYuR7zaAnMUW6TY2vDb35WL2vuCecZgAInQZaF09XC9yqMr4HvFtjkaqGlBnhRmikm9FX0uv6JN5NWpZZ42ydueREcXTZaR+5gT5BWS/qfYTY+8hCQQlC//0kXqkQKnkxJqPEhiQL3iQxPdrHbaq1zGsMnsAbQMgbL6RI/IvSmoTZGMj/PAgDRY3bDpfVtUEfKXXjnV36Di4yeLBGRjEHlQm/5ivl0hkVENfc0dY61Kp0woqogGpvfWnkpN2EhI1BtEkhHe3Rm4ck8fkF7OU8RUhhiiellIvG+89m3MeYn+xKznW6AZ8UbL0/S3K3+Szt5UOLVYxgKOQvg1MmuoLpqvIfx5R+5dzzBKcDrYtIbqot94My1Ynfp1262PpK6zFWOAqSXQt8/Q7p5O90QGPN9I4lCuOEpJvrIG4mlUAPr5/7IYyN3UVNbMt/rbnuTv7eBDlZRqzFxzFqXijdjWyRIY03e4C6aUGEVbpaGL8vK/K4SRvD4cU2G6PhiGlLM1FCsS7SkwXB5l9iTnDTAiva6gzbpCju+z2l+KsaJloZrlONiWmPAgdL5Fedq/x+MM4PSUZG04P5gJyAO+JDUynKLaUKoDkhzsZMM3PblkfqAVZcDPqgKhYvIV9Z7gAN5+ZJd5fPJDYAawW
  template:
    metadata:
      name: alertmanager-discord-webhook
      namespace: kube-system

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-discord-webhook
  namespace: monitoring
spec:
  encryptedData:
    webhook-url: AgBe+flX64nIunVPFC7f8iiXEdkrkxnjlwzSxUFmmh5DanxpRkIflbV0ees8zlekT8yfUZcrpbibU/r3COjBxffNcQZOqghdbtFMzyZyhRr5v1vN1vlJR2GmbGhFZFo+vX6BqHDFbaYwnEEoySJ9yaW/YVGEPGKC7sTqMjsneKNxk11V4XudeIdnmdUQ1frUAGKgfOdjqIFE+vyCdzJo/X/ERJVAs2EK30EO8UWOiEPqoPEgBxwysr0QW2lyLAQKdEjVWVaM0FiwePHUh+4nwgH5eeKAwWYBuJxM9dcUsSMim/nNioCaeBQj2lDqtY583KZTZbWA66C29+soAZdrNigeFAk5Q55UZNPorrt0PTwhCtEsvRh+nMhAOFoJ1QO1x/FVCZ/7pz1VCGU/0ENU3l47QoZOUb2qAK2+PZtN4yeFDfNCrV+vgfhtxBR4iFYXvgRWb++7cGhJSXIQN0kHCxv5pd28Mq8yZX/afVuomoWi57g4iFBkgIkUJfC8MR8bOLDyjT1xt/7Dxra0s1oKFx6eWPTDdqAv4z7PZsuRBZPwRImebjU5wwV3aPCpYJ0UPJO27wHQb/c6Zvj4zfX5m6C5LTEdJPNORkhXR+0sfWkdQl8xKlrNidNtsD1/SEoKRq08bdq3wGbgGUdf/8u/KGjrgEXiXCYL6BcpxwyjpVDfiWASR7cF2blz88Gw0qXbs8fh+n+xa6QEhkRjQl9+7Kk2LZkBmL6QSrhIsvbvxxl8BfsvQFrciAUmMLkI/K4q/Uv4BL+sCSR3Uo9YalfiqxTrvb8nWAGUIGI9h21zLbC5AhY+fBLQoktLYoMj7dDcDldGM/QWfp4x6RbV5H9BjHV8JCNU+PBlI1UF
  template:
    metadata:
      name: alertmanager-discord-webhook
      namespace: monitoring
