---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: wireguard-pvc

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: hdd-general

  resources:
    requests:
      storage: 256Mi
