---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - svc.yaml
  - sealedsecret.yaml
  - alertmanager/alertmanagerconfig.yaml

configMapGenerator:
    - name: routing-config
      files:
        - config.yaml
