---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-webhook-ntfy-svc
spec:
  type: ClusterIP
  selector:
    app: alertmanager-webhook-ntfy-pod
  ports:
    - name: http-webhook-out
      protocol: TCP
      port: 80
      targetPort:  http-webhook
