---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kinv-sa
  namespace: kubeinvaders

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: kinv-cr
# rules:
#   - apiGroups:
#       - ""
#     resources:
#       - pods
#       - pods/log
#     verbs:
#       - delete
#   - apiGroups:
#       - batch
#       - extensions
#     resources:
#       - jobs
#     verbs:
#       - get
#       - list
#       - watch
#       - create
#       - update
#       - patch
#       - delete
#   - apiGroups:
#       - "*"
#     resources:
#       - "*"
#     verbs:
#       - get
#       - watch
#       - list

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: kinv-crb
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: kinv-cr
# subjects:
#   - kind: ServiceAccount
#     name: kinv-sa
#     namespace: kubeinvaders

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   namespace: default
#   name: kubevirt-vm-restart-role
# rules:
# - apiGroups: ["subresources.kubevirt.io"]
#   resources: ["virtualmachines/restart"]
#   verbs: ["update"]

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: kubevirt-vm-restart-binding
#   namespace: default
# subjects:
# - kind: ServiceAccount
#   name: kubeinvaders
#   namespace: kubeinvaders
# roleRef:
#   kind: ClusterRole
#   name: kubevirt-vm-restart-role
#   apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kinv-pod-killer
  namespace: envoy-gateway-system
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kinv-rb
  namespace: envoy-gateway-system
subjects:
- kind: ServiceAccount
  name: kinv-sa
  namespace: kubeinvaders
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kinv-pod-killer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kinv-pod-killer
  namespace: metallb-system
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kinv-rb
  namespace: metallb-system
subjects:
- kind: ServiceAccount
  name: kinv-sa
  namespace: kubeinvaders
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kinv-pod-killer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kinv-pod-killer
  namespace: monitoring
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kinv-rb
  namespace: monitoring
subjects:
- kind: ServiceAccount
  name: kinv-sa
  namespace: kubeinvaders
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kinv-pod-killer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kinv-pod-killer
  namespace: nginx
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kinv-rb
  namespace: nginx
subjects:
- kind: ServiceAccount
  name: kinv-sa
  namespace: kubeinvaders
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kinv-pod-killer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kinv-pod-killer
  namespace: nginx-dev
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kinv-rb
  namespace: nginx-dev
subjects:
- kind: ServiceAccount
  name: kinv-sa
  namespace: kubeinvaders
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kinv-pod-killer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kinv-pod-killer
  namespace: nginx-prod
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kinv-rb
  namespace: nginx-prod
subjects:
- kind: ServiceAccount
  name: kinv-sa
  namespace: kubeinvaders
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kinv-pod-killer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kinv-pod-killer
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kinv-rb
  namespace: default
subjects:
- kind: ServiceAccount
  name: kinv-sa
  namespace: kubeinvaders
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kinv-pod-killer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kinv-pod-killer
  namespace: secrets
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kinv-rb
  namespace: secrets
subjects:
- kind: ServiceAccount
  name: kinv-sa
  namespace: kubeinvaders
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kinv-pod-killer

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: kubedoom-global-viewer
# rules:
# - apiGroups: [""]
#   resources: ["pods"]
#   verbs: ["get", "list", "watch"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: kubedoom-global-viewer-binding
# subjects:
# - kind: ServiceAccount
#   name: kinv-sa
#   namespace: kubeinvaders
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: kubedoom-global-viewer
