---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: vikunja-postgresql

spec:
  instances: 1 # NOTE: Not limited to 1! We can increase this for HA!

  imageName: ghcr.io/cloudnative-pg/postgresql:18.6

  storage:
    size: 2Gi
    storageClass: hdd-general

  bootstrap:
    initdb:
      owner: vikunja
      database: vikunja
