---
apiVersion: v1
kind: Service

metadata:
  name: nginx-svc

spec:
  type: ClusterIP

  selector:
    name: nginx

  ports:
    - name: nginx-http
      protocol: TCP
      port: 80
      targetPort: nginx-http
