---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-webhook-ntfy-env-secrets
  namespace: monitoring
spec:
  encryptedData:
    NTFY_TOKEN: AgAZWjqQl1xiRiuw4MfPPSn5tzIt22e2uqrwy761OVF+Bl0qUDQzja8p54Tmtxn+X4GIOLvi8QSCRjIXMoRkcjtFo93bg39gHHEp+fiiv9kNtHFvoc9KfTvhZGIc6Q1eOoYdttlAkWJSTMHzQNWxdfzhVsETxK1epJSyNCUgXP4OTvetIebngKfB8Qc3k69HUkmbaGH+XFIcjQG/JBTsbND+nyqBWuKbanSyXxydOKQOgN7LBPsn50zB8e1i2hIAvbnTGPdBazPPWWYx8RaQI1oCvWEmyvuasBs7jAExK4lWRzQWK0TgjDOc12qnowxq8jQb1OoS5XjqVZKemwZFUea1u/uVoTp7FoTC0K2Q860yf257JTB3WlFjNKOopfW8OBtohRzuNZAfYckvlKVlajZ0xGOoHqb6Te9QFD6kR1AXQNWA2hD5GbRPxqlAh0Dms/9jvxSdwwCXEMh5lxZrQ0M6SL1Ed/9o2cJBfy2ZwrEMg5jIBq/9a9uJILBjKz/3FPXH015XONPi8Blqo6Oylz+7XDP4BTfYnlEHzGVlg7JvnNZ42Nphx6gGgWlpZYshtIxlLb7q92AQsAyC893gorA1QaVgToF2nhgWRJaGDUgbrYzyMOk0fOLBT5AFhx3+MOnanrs40LJhiuHuMSbqt6K8oO5wUYfhRgwI9/O8N7gdhjwDsH0hYkB1nigXYbWxM3thwigunPiMOHHftmTr+VY+a26ccvyT3tGYu9EoSearCA==
  template:
    metadata:
      name: alertmanager-webhook-ntfy-env-secrets
      namespace: monitoring
