---
# REF: https://cloudnative-pg.io/docs/1.30/declarative_role_management
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: immich-redis-postgres-role
spec:
  cluster:
    name: immich-postgresql
  name: immich-redis-postgres
  comment: "immich super-user"
  login: true
  superuser: true
  createdb: true
  databaseRoleReclaimPolicy: retain
