---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: immich-postgresql

spec:
  instances: 1 # NOTE: Not limited to 1! We can increase this for HA!

  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18.4-1.1.1

  storage:
    size: 2Gi
    storageClass: hdd-general

  bootstrap:
    initdb:
      owner: immich
      database: immich

      postInitSQL:
        - ALTER USER immich WITH SUPERUSER; # NOTE: https://docs.immich.app/administration/postgres-standalone/#with-superuser-permission

      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS "vchord" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "cube";
        - CREATE EXTENSION IF NOT EXISTS "earthdistance";

  postgresql:
    shared_preload_libraries:
      - "vchord.so"
