---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: immich-data

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: hdd-general

  resources:
    requests:
      storage: 20Gi
