---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Source: https://raw.githubusercontent.com/projectcalico/calico/v3.32.1/manifests/custom-resources.yaml
# Which is from: https://docs.tigera.io/calico/latest/getting-started/kubernetes/quickstart

resources:
  - https://raw.githubusercontent.com/projectcalico/calico/v3.32.1/manifests/v3_projectcalico_org.yaml
