---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: immich-postgresql

spec:
  instances: 1 # NOTE: Not limited to 1! We can increase this for HA!

  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18.4-1.1.1

  storage:
    size: 2Gi
    storageClass: hdd-general
