# Trying to learn how to make a kubeconfig file to distribute that has limited permissions.
# This one will be for the kubedoom namespace only, limiting it to only port-forwarding.
#
# From what I understand, there of course has to be a namespace for the ServiceAccount resource.
# Then I'll be making it the default namespace in the kubeconfig, and the only namespace it can
# touch. That ServiceAccount needs permissions to do things, which uses the whole Role-Based Access Control
# system. So, there's a role with the permissions, and the role binds to the ServiceAccount with
# a RoleBinding. Then to be able to construct a kubeconfig, I need to generate a token that expires.
# Using my own kubeconfig file as a template, I can replace parts of it for the new kubeconfig.
# But, I also need to replace the `client-certificate-data` and `client-key-data` fields with
# just `token`.
#
# Now, the commands:
#
# `kubectl config view --raw -o jsonpath='{.clusters[0].cluster.certificate-authority-data}'`
# replaces the `certificate-authority-data`
#
# `kubectl create token kubedoom-bot -n kubedoom --duration=8760h`
# is what replaces the token. It makes a token that is valid for 1 year.
#
# Then that should work! I should probably change instances of `kubernetes-admin` to something else.
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubedoom

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubedoom-bot
  namespace: kubedoom

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubedoom-role
  namespace: kubedoom
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubedoom-role-binding
  namespace: kubedoom
subjects:
- kind: ServiceAccount
  name: kubedoom-bot
  namespace: kubedoom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubedoom-role

# Now my file looks like this:
# apiVersion: v1
# clusters:
# - cluster:
#     certificate-authority-data: <>
#     server: https://<IP>:<PORT>
#   name: kubernetes
# contexts:
# - context:
#     cluster: kubernetes
#     namespace: kubedoom
#     user: kubedoom-bot
#   name: kubedoom-bot
# current-context: kubedoom-bot
# kind: Config
# users:
# - name: kubedoom-bot
#   user:
#     token: <>