---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubedoom-rbac
  # namespace: kubedoom

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: kubedoom
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: cluster-admin
# subjects:
#   - kind: ServiceAccount
#     name: kubedoom
#     namespace: kubedoom

# 100% DO NOT ALLOW:
# - kube-system
# - tigera-operator
# - calico-system
# - nfs-provisioner

# Currently allowing:
# - envoy-gateway-system
# - metallb-system
# - argocd (debating on it)
# - monitoring
# - nginx
# - nginx-dev
# - nginx-prod
# - default
# - secrets

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubedoom-pod-killer
  namespace: envoy-gateway-system
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubedoom-binding
  namespace: envoy-gateway-system
subjects:
- kind: ServiceAccount
  name: kubedoom-rbac
  namespace: kubedoom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubedoom-pod-killer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubedoom-pod-killer
  namespace: metallb-system
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubedoom-binding
  namespace: metallb-system
subjects:
- kind: ServiceAccount
  name: kubedoom-rbac
  namespace: kubedoom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubedoom-pod-killer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubedoom-pod-killer
  namespace: argocd
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubedoom-binding
  namespace: argocd
subjects:
- kind: ServiceAccount
  name: kubedoom-rbac
  namespace: kubedoom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubedoom-pod-killer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubedoom-pod-killer
  namespace: monitoring
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubedoom-binding
  namespace: monitoring
subjects:
- kind: ServiceAccount
  name: kubedoom-rbac
  namespace: kubedoom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubedoom-pod-killer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubedoom-pod-killer
  namespace: nginx
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubedoom-binding
  namespace: nginx
subjects:
- kind: ServiceAccount
  name: kubedoom-rbac
  namespace: kubedoom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubedoom-pod-killer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubedoom-pod-killer
  namespace: nginx-dev
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubedoom-binding
  namespace: nginx-dev
subjects:
- kind: ServiceAccount
  name: kubedoom-rbac
  namespace: kubedoom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubedoom-pod-killer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubedoom-pod-killer
  namespace: nginx-prod
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubedoom-binding
  namespace: nginx-prod
subjects:
- kind: ServiceAccount
  name: kubedoom-rbac
  namespace: kubedoom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubedoom-pod-killer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubedoom-pod-killer
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubedoom-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: kubedoom-rbac
  namespace: kubedoom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubedoom-pod-killer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubedoom-pod-killer
  namespace: secrets
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubedoom-binding
  namespace: secrets
subjects:
- kind: ServiceAccount
  name: kubedoom-rbac
  namespace: kubedoom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubedoom-pod-killer
