---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: mc-i-1b163d47-deployment
  labels:
    app: mc-i-1b163d47-deployment

spec:
  replicas: 1
  revisionHistoryLimit: 1
  # Kubernetes tries to spin up a new pod before terminating the old one.
  # This will ensure the old pod lets go of the ReadWriteOnce PVC before the new one is created so that the new one can grab the PVC.
  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: mc-i-1b163d47-pod

  template:
    metadata:
      labels:
        app: mc-i-1b163d47-pod

    spec:
      initContainers:
        - name: init-configs
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              echo "Copying configuration files."
              mkdir -p /data/plugins/AuthMe
              mkdir -p /data/plugins/SkinsRestorer

              cp /tmp/configs/purpur.yml /data/purpur.yml
              cp /tmp/configs/bukkit.yml /data/bukkit.yml
              cp /tmp/configs/spigot.yml /data/spigot.yml

              cp /tmp/configs/authme-config.yml /data/plugins/AuthMe/config.yml
              cp /tmp/configs/skinsrestorer-config.yml /data/plugins/SkinsRestorer/config.yml

              echo "Configs successfully deployed!"

          volumeMounts:
            - name: mc-i-1b163d47-data
              mountPath: /data

            - name: mc-i-1b163d47-configs
              mountPath: /tmp/configs

      containers:
        - name: mc-i-1b163d47
          image: itzg/minecraft-server:latest

          env:
            - name: EULA
              value: 'TRUE'
            - name: TYPE
              value: 'FABRIC'
            - name: VERSION
              value: 'LATEST'
            - name: MEMORY
              value: '2048M'
            - name: MAX_PLAYERS
              value: '7'
            - name: MOTD
              value: |-
                  §9Kubernetes §2Minecraft §6Server
                          §n§dmc.sidewinder.lan§d
            - name: ICON
              value: '/icon/icon.png'
            - name: OVERRIDE_ICON
              value: 'true'
            - name: ONLINE_MODE
              value: 'false'
            - name: USE_AIKAR_FLAGS
              value: 'true'
            # Purpur only
            # - name: USE_SIMD_FLAGS
            #   value: 'true'
            - name: SEED
              value: 'KubernetesMC'
            - name: SPAWN_PROTECTION
              value: '0'
            - name: OPS
              value: |-
                CMDR_JohnAlex
            - name: EXISTING_OPS_FILE
              value: 'MERGE'
            - name: ENABLE_WHITELIST
              value: 'false'
            - name: MODRINTH_PROJECTS
              value: |-
                fabric-api
                skinsrestorer
                easyauth
                sodium
                entityculling
                ferrite-core
                lithium
                xaeros-minimap
                xaeros-world-map
                simple-voice-chat
                sound-physics-remastered
                chat-heads
                carry-on
                netherportalfix
                imblocker-original
                farmers-delight-refabricated
                more-delight
                appleskin
                jei
              # https://modrinth.com/resourcepack/enhanced-boss-bars
              # https://modrinth.com/resourcepack/cubic-sun-moon
              # https://modrinth.com/resourcepack/vvi
              # https://modrinth.com/resourcepack/clean-connected-glass
              # https://modrinth.com/resourcepack/glowing-glints
            - name: MODRINTH_DOWNLOAD_DEPENDENCIES
              value: 'required'
            - name: MODRINTH_ALLOWED_VERSION_TYPE
              value: 'beta'
            - name: BROADCAST_CONSOLE_TO_OPS
              value: 'false'
            - name: BROADCAST_RCON_TO_OPS
              value: 'false'
            - name: ANNOUNCE_PLAYER_ACHIEVEMENTS
              value: 'true'
            - name: LOG_TIMESTAMP
              value: 'true'
            # - name: JVM_XX_OPTS
            #   value: >-
            #     -XX:ABC

          ports:
            - containerPort: 25565
              name: i-1b163d47-tcp
            - containerPort: 24454
              name: i-1b163d47-udp

          resources:
            limits:
              cpu:  2500m
              memory: 3000Mi
            requests:
              cpu: 1000m
              memory: 2000Mi

          startupProbe:
            exec:
              command:
                - mc-health
            initialDelaySeconds: 0
            # 5 minutes to start up:
            periodSeconds: 10
            failureThreshold: 30
            # 5 seconds to reply:
            timeoutSeconds: 5

          livenessProbe:
            exec:
              command:
                - mc-health
            # 2.5 minutes (5 missed messages) before death:
            periodSeconds: 30
            failureThreshold: 5
            # 5 seconds to reply:
            timeoutSeconds: 5


          readinessProbe:
            exec:
              command:
                - mc-health
            periodSeconds: 30
            failureThreshold: 5
            timeoutSeconds: 5

          volumeMounts:
            - name: mc-i-1b163d47-data
              mountPath: /data

            - name: mc-i-1b163d47-icon
              subPath: emoji_u1f359.png
              mountPath: /icon/icon.png

      volumes:
        - name: mc-i-1b163d47-data
          persistentVolumeClaim:
            claimName: mc-i-1b163d47-data

        - name: mc-i-1b163d47-configs
          configMap:
            name: mc-i-1b163d47-configs

        - name: mc-i-1b163d47-icon
          configMap:
            name: mc-i-1b163d47-icon
