---
# https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#bases-and-overlays
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - pvc.yaml
  - svc.yaml
  - gateway.yaml

  - nginx

configMapGenerator:
    - name: mc-i-1b163d47-configs
      files:
        - configs/skinsrestorer-config.yml

    - name: mc-i-1b163d47-icon
      files:
        - icon/emoji_u1f359.png
