---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mc-i-36f8a5b8-data

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: nfs-client

  resources:
    requests:
      storage: 5Mi
