---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mc-i-1b163d47-data

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: usb-flash

  resources:
    requests:
      storage: 5Mi
