server {
    listen 80;
    server_name _; # Normally this would be the domain URL (example.com) but we're using `_` as a catch-all.

    # Hide nginx version
    server_tokens off;

    root /usr/share/nginx/html; # Set root to the standard NGINX location. Things are now relative to this.

    # Block common scrapers
    if ($http_user_agent ~* (scrapy|curl|wget|python|aiohttp|httpx|bot|crawler|spider)) {
        return 403;
    }

    # Tells compliant search engines:
    #   * Do not index this folder.
    #   * Do not follow links.
    #   * Do not archive content.
    add_header X-Robots-Tag "noindex, nofollow, noarchive";

    location / { # So match /anything unless a more specific location is defined.
        try_files $uri $uri/ /index.html =444; # Try those in order. =444 is a non-standard return code where NGINX will say, "if nothing exists, DROP CONNECTION" (doesn't seem to work?)

        index index.html; # If directory requested, look for index.html
        disable_symlinks on;
    }

    # robots.txt
    location = /robots.txt {
        try_files $uri =404;
    }
}
