---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCov7hW01Z4YveS2Al9haGlPhOcBoeWjo6mayHGEOD14jCFjtVjiZtO205L+Vdv49vS7d1yhXtxhk2j5awNdFNRXQz2JfiCOycWeywl8tHGuCHtOTofVeJcQKkDrppQKRhpP6hRP1KnHOTIeZJU+nRJlniCtCDcW4AIxCS4krpW9WW+8Le6XT7x3SZLJPWVacwHwvR+yZfXPHZfMtkmYJF926OFji3c/cLMBUX7gjxTE4YWYMW5J/MfGOVhA/cliadbnF2cQM7XsYCtLuhGFI7WrLqdtSQ9qZtox5OTKPHD87a7izxGRUqKgsuirUR1gUvZbCKZYlApKexAHle4jsbHan2eWw9hJvAmovgvvpFvMFwbAumwbMLioJg2ai9KRR6kh3PiFN1ROxpBoFyQUEws1Y93Nj4UhIeP8THsZj669nys9rk+tDE9V3qzhnOYk2LeLdyQN+EqYbN8YrCJFK3xgnI96i9mXj4D/x0lDk3M0E7dU/LN8pXac8tBMX4edswhdAtACIVv32s3rxezD2+cMyDiFA5TRvcrPpvnkwsrLrAreq2R6h88pPK4zI8r6iFtI2Ba3Z+ScS6elQaxvbOKkiIb2vvWCraNHCn9LaMBB2w5o9x8iGGXvzbt6FlCHERZPvLWLX6ZH/spZTBI+xbfB1q+ecigPGrmYWSTxhS/XS4LSrO725CJTcZCeBIKMiroVntqD2tdcIh1BAuk5kvWg5NRzxafQnZdz27cE8RBawNX1+RVhJ64TaAQ15KFTPx0wraRhVfkV7I=
    admin-user: AgCz9EKt0SqTAFJ+M6yP9bWh1TYNkxayfXO18qElAdjD0spKx9pPQABD/Rhc5qp/wP3Jgc6YkG2hXqoAoX4TpNheSLVCCgbv0yrtsbVBH6pnyBcaV1M0drnAkcGIAEYcT13/bM5oonZVzFnG/OWb3L4qDN0JOfEwDaK5028EHx0fQAv/jnICxq5mRQP+X4dJEyDNvHR31nH5RD//D6Up1Y01584dcJ4SUTVoJqOWWtkOnCRINfClPqTCjsVgXtVrOJCRBQYzLXoZotuEokIZKFE9BEQutkASbVDIgeiQA/nwnKVHBkAfBqjkMonMzyFX9NkofXkstHDQoV4nLakhDLo5+YJziweWQl/V+2AiLCoEjGiW3mCdICyz/cYCpzfZbJ1+v6FEZdhz+5+3rkKdZkHCieG2Dh7DTJ/IOv3tr7yD8NAFobRMuy/mH7DwKGiOR8CZce3aRi7uyHkFwCb/HkYJZV5aXnjoNxiLjXGnX2wbTMSjLBpinLSokKLmc/wIL2qXK+3kcf3Rtw6D4Y8RfecBfvd/2q7CvLKdKl+GllroKTj6rPFhcWCqrbmY12yOfREHbbTNQBuD3zHAKSqrU0seFhOp0fOZEI+Mlz4Xh5e6HTSbdmu/9H5F0aTWWRXlhGOHqidyaejnNtHaqMRsmw+KYHJuHKZZ2+8owKodDSZi89brYOjBQbksIVZzx34FCx5vdkSmgA==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
