---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: nginx-i-2t6sqrjy-data

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: usb-flash

  resources:
    requests:
      storage: 1Mi
