---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: navidrome-data

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: hdd-general

  resources:
    requests:
      storage: 5Mi
