---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cnpg-db-secrets
  namespace: git
spec:
  encryptedData:
    password: AgCntN8dJOh2PsNKr1i52MUcr7Lz/+Kaqa29fWznXZh0ksDIOKMByiemm+jGMpsvNuzIHVf/LwFWA0l9d7evgOoQseB9BRRlQcnKla84hvPrpb+evv+OOgrDJLnUUmfOccwckwDG5l2O1O6iRSEd8L71P23zYf8TKbAOUqjpSK08fAEoiAOCiCfDKpSQORp1n1lp1ekCQoum/AERFHRCNerrYmrx3C7N8E87I9IkiJ4Ic/+0iaUfoawol6Mi6VWcRGviREhrdzznXP+a+wWoaPTHlzsrHe/0F5dwc9KfhyAnifxPEcf5Ue0cjkPjKZfmNbp6j9TAw3EG+fI+UJLgwSQdpaP+H7cBRfv0zp+y6pfQ0mh7TKOXtDUQnnmubfyApR6Lz8Dcv7fIzvloUBrv5O6rqR9xRhrAgSOW+SwsaJWK6mfCL/V3AKKv4R0sGRA1grn85wBoulcLNPEDgUWZZti7gXjvi34hjIKH8PVMz+ixiTwte1HKPoRdbfHUTudJOACmfp+Y6ss+W9RDD/PNckgIGZPby2/A/qHRCOIhFHg7hsNTAsuGlP6OBcRUen1vqPCL/CHPcjS6pP/tZOWJPxplUneoSnHo1Zo/EGZkWYdgifS6BtX0Xp1q/QwCmcLLkKgjLcity1UdK8L6kCm2YGSmZAG8I86gbBwXw+zXe9ifaDJOogNkXol9KrlFvEFwEia7JqscfAqltvG6xrwKOLkSzpWbjcqGfTf2XhHanHaDYth93F8/g6B91Elt65/0MLn4jeGBEVlxLT4X9wTM0exfuN3KlSllBmMyClJV+4qw12efOvAvTfdO
    username: AgCE1JyhFKAKPP2SOaEbe+z/wv9LMHj8S62ZuMrxg7IPcWU0+66yTBSH+A/JZe21NXpsOm28pXImKoLpvugdE5gHpKZ9lROfwVWVu0+fO1aY5cQMBrAy0F+SkTqz+TzUd0CKZTE1pg5RHDRc5In/v2FQHFfIXz0JAT4gNoLX8beNp9KeagD88LDOVBEM2IRjIWZInQFdfSuHscMXwUVBA8ntiuTLj2PUaWyooGvCRt4GmqDf0d8Q/I8mRmBG/3LHJZ4FbP4onr48DAwvs9vuVPFgeF9KXSuYkJ+wCYHVzRGSenNXrpl/5aBeRl7WMQ8Hgz7gac1FImKDqfRwZIFqo56jX3F9dRNWBokPu8wYjpXPQLv0pYNfXJXkUaNWhSVg/9GzPKtLRaZD4z4PokMbxw0zcaena/9FOlwhMHvkouvjOxwVYA07B6dyKy1ZpmybyddWYELSv212p8ausPAyJoSuUBBJmQGIBQYYp/uxlECr44p6OaJJDcDI0e81LrwAemiAultn7xkOLpT+viYQE3kx+pypXsDmbkqJqp+fiqjH9ale2aH0SwGrQLcdEW5QnmN4dHyPmM6GvnHlJ46hG+WIj/11/0ndj6wTedf4vyIoN+HuymNST2WQOfKGpAiGpx+4TyH9iEkum6FlMeSw8WppipZYUbGw85NTj4GMe9MdXzTmV0hgoMtHlQsql+vBAlLxk05Fd0Mn
  template:
    metadata:
      name: cnpg-db-secrets
      namespace: git
