---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

  - sealed-secret.yaml

patches:
  - path: cnpg-cluster-patch.yaml
  - path: gateway-patch.yaml

labels:
  - pairs:
      instance: prod
    includeSelectors: false
    includeTemplates: true
