---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vikunja-secrets
  namespace: vikunja-prod
spec:
  encryptedData:
    database-password: AgA3XCoedTZDz2ls5F6m2CAzBObNfmlnevSUruGwG7SS64Rk7n0fyPf1xtKC3oLxNEVkgG+KFZ+cLW75upPp/CLr41MaPj0J5xYPiMtwDiWYbjmqLk1rIbehb7owb0Fxwp+gMxUMr/lUzgDPCoMKESbVkLK69cMh5VjK7Bksy6WS4GlROQocwbhw+Zvj4oWnZEYbnQYvFb+UFYVOGkEWvFfhyHRbvS+Fx2qryZkZyeAxwNE2GfMj6iQnxWfoi3LA12XsHJ7o/cEj+EMjNaHsTUS8YnPdOJF/UtrblQNZ77i3RouAmLOfsYf15KFNDhtCXFBn+Bv+Yw+6TBLfVmuZA/h6vdcZCK+FQgVwhDdceLd0PUMNNdZirvqeyZ/VXOeSTtPoy3IrEU1lIOyutMIUoPmaBW9XwRz58fDlmRMsER0L9dI3zW1mKwgJwIZNbibHdKinEEPtxOqL6Z0FWptI1eqpbgw8iRTPZdLr/0MhhYm6MbbPdiQeTp1r6OjcjdqKxL9IekwQzMuqxX2Wwrl+ZsNZd63lyCsrrXKoL0KZNyNmeEDuHpKp5y/IwyWacW8l+WNp+ve4gZf+HLhp7yRnFp6UUiOenMc8LPWbUA/DGaif+4x66YjFYDI0ympJdMfOl5U2RqivCn1RvS7AFoSGz5CVpnuVlVwgGJsSud1MVGX/Qme8j4GmnRefVA9/543rqakfaFIIAiTDJVoZWtBdo6qM0t9Hu50U9l3wywBeqBQUlLc8VDdMCxCoz4L/ujN+q3fLgQta2LJBJuHalw8Ps5Ti8Xx8SuijtFBzv6n7DMzVSWR7HPUHYcpzSh6i48KtJeEw7MLH7Yy+plWq92X6xq4hnF5+UNrlc925kkTedgF0/JSGGkQE8qDZHmfQxBFM9PNUBxCa8/P1PhEjOcfnysF3cgCYKoDcTUqs6YflHzWg3sJXLUnmyMwVz993ngwcpAGhXxIsJRF9eIXv+IqbFFooqK1ZXLvq//qQoPbr3ivbTpS5c2DVUhIjbnK5KAM3N9gBC9EOvYsoCNrFRTPjdW6BL3C8urektqaJP5uyeGGePnPeGtIV8prWesqlFBma12tscUwB/JhY/ewv9GaZD+KO/F12gxsjB7j+HoBEaxGfoOvvbZ/qx5TS3INSVqjkxX63NtSjqPFrBg==
  template:
    metadata:
      name: vikunja-secrets
      namespace: vikunja-prod
