---
# -- Number of replicas (pods) to launch.
replicaCount: 0

# -- Number of old ReplicaSets to retain to allow rollback.
revisionHistoryLimit: 3

# -- Additional storage [volumes](https://kubernetes.io/docs/concepts/storage/volumes/).
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#volumes-1) for details.
volumes: # []
  - name: nfs-8dafdf36-cb0f-4102-a05e-d69ea5954303
    nfs:
      server: 192.168.7.7
      path: /mnt/nfs/8dafdf36-cb0f-4102-a05e-d69ea5954303

  - name: nfs-e9642e46-dd2e-4900-be52-4eb23e67cbf5
    nfs:
      server: 192.168.7.7
      path: /mnt/nfs/e9642e46-dd2e-4900-be52-4eb23e67cbf5

  - name: sftpgo-data
    persistentVolumeClaim:
      claimName: sftpgo-data-pvc

# -- Additional [volume mounts](https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/).
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#volumes-1) for details.
volumeMounts: # []
  - name: nfs-8dafdf36-cb0f-4102-a05e-d69ea5954303
    mountPath: /srv/nfs-8dafdf36-cb0f-4102-a05e-d69ea5954303

  - name: e9642e46-dd2e-4900-be52-4eb23e67cbf5
    mountPath: /srv/e9642e46-dd2e-4900-be52-4eb23e67cbf5

  - name: sftpgo-data
    subPath: srv/sftpgo/
    mountPath: /srv/sftpgo

  - name: sftpgo-data
    subPath: var/lib/sftpgo/
    mountPath: /var/lib/sftpgo
