---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-ntfy-config

data:
  config.yml: |
    http:
      addr: ":8080"

    ntfy:
      baseurl: "http://ntfy-svc.monitoring.svc.cluster.local:80"

      notification:
        topic: "all-alerts"
        priority: "status == 'firing' ? 'high' : 'default'"

        tags:
          - tag: "+1"
            condition: "status == 'resolved'"
          - tag: "rotating_light"
            condition: "status == 'firing'"

        templates:
          title: "{{ if eq .Status 'resolved' }}Resolved: {{ end }}{{ index .Annotations 'summary' }}"
          description: "{{ index .Annotations 'description' }}"
