---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-ntfy
  labels:
    app: alertmanager-ntfy

spec:
  replicas: 1

  selector:
    matchLabels:
      app: alertmanager-ntfy

  template:
    metadata:
      labels:
        app: alertmanager-ntfy

    spec:
      containers:
        - name: alertmanager-ntfy
          image: ghcr.io/alexbakker/alertmanager-ntfy:latest

          ports:
            - containerPort: 8080
              name: http-internal

          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi

          volumeMounts:
            - name: config-volume
              mountPath: /etc/alertmanager-ntfy

      volumes:
        - name: config-volume
          configMap:
            name: alertmanager-ntfy-config
